### ISSUE TITLE
Gathering All Data from Get-CsUserSession

### ISSUE THREAD

**Issue by Drabert** [jasonshave/CxdCallData#2]
Thank you very much for all the work on this script.  I am working off of this [https://blogs.msdn.microsoft.com/mahmoud_badran/2017/11/04/skype-for-business-rate-my-call-with-power-bi-analysis/](url) to try to build some call quality dashboards in Power BI but for some reason, it seems like i am missing some data.  I ran the query for 30 days and it gave me 3000 records, but looking at the microsoft CQD im seeing almost 4000 calls a day.  I saw a comment in another thread about hitting the 1000 records limit, but was not sure if that was already resolved in the current version or if there is something that needs to be edited to get all of the results? thank you again for the awesome script!

**Comment by jasonshave** [comment]
Hey thanks for the feedback. The script should be pulling all data from Get-CsUserSession if the results are greater than 1000 records. We've seen this module used at some very large customers who pull a lot of data daily without issue. If you're looking at CQD data are you sure you're not mixing the concept of a call with a 'stream'?

**Comment by Drabert** [comment]
Thanks for the response Jason.  What i was seeing is that if i run the Get-CsUserSession for an id and then look at what was pulled from the script, there are more items returned than if I run your script.  I ended up modifying this line
`[array]$processedFeedback = $audioSessions | Where-Object {$_.QoeReport.FeedbackReports} | ProcessFeedback`

It looks like the script is just processing calls that have a feedback report, but some of the calls what i am seeing do not.  They still have call quality metrics about Jitter and Latency but just no feedback report.  Are these calls i should not be looking at for metrics?

Thanks again for the powerful script!!!

**Comment by jasonshave** [comment]
The code you provided is referenced in the RateMyCallFeedback function which serves to extract RMC feedback report data. There are cases where a QoE report is missing, or in some cases, no RMC prompt was given. Because of this, it wouldn't make sense to build a report for RMC feedback where most of the records were just regular calls (either without a QoE report attached, or RMC feedback solicited). 

Sounds like you might be looking for a report listing all calls rather than being filtered. Is this correct?

**Comment by jasonshave** [comment]
A report has been built for this in the latest version published on PSG.
